### ISSUE TITLE
개발환경 구축 (Server)

### ISSUE THREAD

**Issue by elvortion** [infinitefire/IssueTrackingSystem#2]
### 목적
* AWS 클라우드 서버를 이용한 개발 환경을 구축한다.

### 진행
- [x] 프로젝트에 필요한 AWS 서버 인스턴스 생성
- [x] AWS 개발 서버에 nginx와 tomcat 설치 및 연동
- [x] 쉘 스크립트를 통한 배포 자동화

**Comment by hihihot2** [comment]
EC2 - Ubuntu 생성 / JAVA  Tomcat  mysql  설치

**Comment by hihihot2** [comment]
EC2 - nginx 설치 및 배포 자동화 설정 : ~/service-up.sh
